from .fuel import FuelDisbursementSerializer,SubProgrammeSerializer,ProgrammeSerializer,FuelReceivedSerializer,FuelAllocationSerializer
from .maintenance import MaintenanceCloseSerializer,MaintenanceSerializer
from .mileage import MileageRecordSerializer
from .vehicles import ProvinceSerializer,LocationSerializer,VehicleSerializer,StatusSerializer,UserProfileSerializer,FuelTypeSerializer