# Generated by Django 5.0.3 on 2024-04-21 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subProgramme_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_litres', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('monthly', models.CharField(max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('fueltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.province')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=1000)),
                ('subProgramme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.subprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='FuelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_litres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('fuel_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='vehicles.fuelreceipt')),
                ('subProgramme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.subprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.location')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('engine_number', models.CharField(max_length=100)),
                ('classis_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fueltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.fueltype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.location')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.province')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.status')),
            ],
        ),
        migrations.CreateModel(
            name='MileageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_reading', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_records', to='vehicles.userprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service_mileage', models.IntegerField()),
                ('is_serviced', models.BooleanField(default=False)),
                ('before_next_service_mileage', models.IntegerField()),
                ('next_service_mileage', models.IntegerField()),
                ('next_service_date', models.DateField(null=True)),
                ('service_date', models.DateField(auto_now_add=True, null=True)),
                ('service_type', models.CharField(max_length=500, null=True)),
                ('service_provided', models.CharField(max_length=1000, null=True)),
                ('service_provider', models.CharField(max_length=1000, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('cost_incurred', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_at_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_status', to='vehicles.status')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=1000)),
                ('amount_of_fuel_disbursed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coupon_serial_number', models.CharField(max_length=50)),
                ('issuer_name', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.programme')),
                ('subProgramme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.subprogramme')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.userprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
