# Generated by Django 5.0.3 on 2024-03-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subProgramme_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fueldisbursement',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.programme'),
        ),
        migrations.AddField(
            model_name='programme',
            name='subProgramme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.subprogramme'),
        ),
        migrations.AddField(
            model_name='fueldisbursement',
            name='SubProgramme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.subprogramme'),
        ),
    ]
