# Generated by Django 5.0.3 on 2024-03-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_programme_subprogramme_fueldisbursement_programme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueldisbursement',
            old_name='SubProgramme',
            new_name='subProgramme',
        ),
    ]
