# Generated by Django 5.0.3 on 2024-03-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_subprogramme_fueldisbursement_subprogramme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueldisbursement',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='fueldisbursement',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleuser'),
        ),
    ]
