# Generated by Django 5.0.3 on 2024-04-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_fueltype_vehicle_fueltype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='fueltype',
            new_name='fuel_type',
        ),
    ]
