# Generated by Django 5.0.3 on 2024-03-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_fueldisbursement_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='next_service_date',
            field=models.DateField(null=True),
        ),
    ]
