# Generated by Django 5.0.3 on 2024-04-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_fueltype_fueltype_fuel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='fuel_type',
            new_name='fuel_type_name',
        ),
    ]
