# Generated by Django 5.0.3 on 2024-04-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_fuel_type_fueltype_fuel_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fueltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='FuelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_litres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('subProgramme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.subprogramme')),
                ('fuel_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='vehicles.fuelreceipt')),
            ],
        ),
    ]
