# Generated by Django 5.0.3 on 2024-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_maintenance_next_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='service_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
