# Generated by Django 5.0.3 on 2024-04-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_fuelreceipt_fuelallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreceipt',
            name='distribution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fuelreceipt',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
