# Generated by Django 5.0.3 on 2024-04-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_fuelreceipt_distribution_fuelreceipt_is_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelreceipt',
            old_name='distribution',
            new_name='monthly',
        ),
    ]
